parameters:
#    scube_admin_settings.example.class: Scube\AdminSettingsBundle\Example

services:
#    scube_admin_settings.example:
#        class: %scube_admin_settings.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
