parameters:
#    scube_torrent.example.class: Scube\TorrentBundle\Example

services:
#    scube_torrent.example:
#        class: %scube_torrent.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
