parameters:
#    scube_facebook.example.class: Scube\FacebookBundle\Example

services:
#    scube_facebook.example:
#        class: %scube_facebook.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
