ScubeAdminAppearanceBundle_homepage:
    pattern:  /admin_appearance
    defaults: { _controller: ScubeAdminAppearanceBundle:AdminAppearance:index }
ScubeAdminAppearanceBundle_theme:
    pattern:  /admin_appearance/{theme}
    defaults: { _controller: ScubeAdminAppearanceBundle:AdminAppearance:index }
ScubeAdminAppearanceBundle_set_current:
    pattern:  /admin_appearance_set_current/{theme}
    defaults: { _controller: ScubeAdminAppearanceBundle:AdminAppearance:setCurrent }