parameters:
#    scube_account.example.class: Scube\AccountBundle\Example

services:
#    scube_account.example:
#        class: %scube_account.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
