parameters:
#    scube_my_apps.example.class: Scube\MyAppsBundle\Example

services:
#    scube_my_apps.example:
#        class: %scube_my_apps.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
