ScubeProfileViewerBundle_homepage:
    pattern:  /profile/{id_user}
    defaults: { _controller: ScubeProfileViewerBundle:ProfileViewer:newsfeed }

ScubeProfileViewerBundle_newsfeed:
    pattern:  /profile/newsfeed/{id_user}
    defaults: { _controller: ScubeProfileViewerBundle:ProfileViewer:newsfeed }
ScubeProfileViewerBundle_postlist:
    pattern:  /profile/newsfeed_posts/{id_user}
    defaults: { _controller: ScubeProfileViewerBundle:ProfileViewer:postList }
ScubeProfileViewerBundle_newsfeed_remove:
    pattern:  /profile/newsfeed/remove/{id_user}/{id_news}
    defaults: { _controller: ScubeProfileViewerBundle:ProfileViewer:newsfeedRemove }

ScubeProfileViewerBundle_infos:
    pattern:  /profile/infos/{id_user}
    defaults: { _controller: ScubeProfileViewerBundle:ProfileViewer:infos }
ScubeProfileViewerBundle_pics:
    pattern:  /profile/pics/{id_user}
    defaults: { _controller: ScubeProfileViewerBundle:ProfileViewer:pics }
