ScubeAccountBundle_homepage:
    pattern:  /edit_account
    defaults: { _controller: ScubeAccountBundle:Account:editAccount }
ScubeAccountBundle_edit_email_password:
    pattern:  /edit_email_password
    defaults: { _controller: ScubeAccountBundle:Account:editEmailPassword }
ScubeAccountBundle_edit_profile:
    pattern:  /edit_profile
    defaults: { _controller: ScubeAccountBundle:Account:editProfile }
ScubeAccountBundle_edit_picture:
    pattern:  /edit_picture
    defaults: { _controller: ScubeAccountBundle:Account:editPicture }
ScubeAccountBundle_social_networks:
    pattern:  /edit_social_networks
    defaults: { _controller: ScubeAccountBundle:Account:editSocialNetworks }
ScubeAccountBundle_social_networks_confirm:
    pattern:  /social_networks_confirm
    defaults: { _controller: ScubeAccountBundle:Account:socialNetworksConfirm }