AdminAppsBundle_homepage:
    pattern:  /admin_apps
    defaults: { _controller: ScubeAdminAppsBundle:AdminApps:index }
AdminAppsBundle_activate:
    pattern:  /admin_apps_activate/{id}/{val}
    defaults: { _controller: ScubeAdminAppsBundle:AdminApps:activate }
AdminAppsBundle_remove:
    pattern:  /admin_apps_remove/{id}
    defaults: { _controller: ScubeAdminAppsBundle:AdminApps:remove }
AdminAppsBundle_install:
    pattern:  /admin_apps_install
    defaults: { _controller: ScubeAdminAppsBundle:AdminApps:install }