parameters:
#    scube_manage_document.example.class: Scube\ManageFileBundle\Example

services:
#    scube_manage_document.example:
#        class: %scube_manage_document.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
