ScubeBaseBundle:
    resource: "@ScubeBaseBundle/Resources/config/routing.yml"
    prefix:   /

ScubeFriendsBundle:
    resource: "@ScubeFriendsBundle/Resources/config/routing.yml"
    prefix:   /

ScubeManageFileBundle:
    resource: "@ScubeManageFileBundle/Resources/config/routing.yml"
    prefix:   /

ScubeAdminAppsBundle:
    resource: "@ScubeAdminAppsBundle/Resources/config/routing.yml"
    prefix:   /

# Internal routing configuration to handle ESI
#_internal:
#   resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#   prefix:   /_internal
