ScubeFacebookBundle_homepage:
    pattern:  /facebook
    defaults: { _controller: ScubeFacebookBundle:Default:index }
    
ScubeFacebookBundle_login_check:
    pattern:  /login_check
    defaults: { _controller: ScubeFacebookBundle:Default:index }
    
ScubeFacebookBundle_logout:
    pattern:  /facebook_logout
    defaults: { _controller: ScubeFacebookBundle:Default:logout }