AdminUserBundle_homepage:
    pattern:  /admin_user
    defaults: { _controller: ScubeAdminUserBundle:AdminUser:index }
AdminUserBundle_user_edit:
    pattern:  /admin_user_user_edit/{id}
    defaults: { _controller: ScubeAdminUserBundle:AdminUser:editUser } 
AdminUserBundle_groups:
    pattern:  /admin_user_groups
    defaults: { _controller: ScubeAdminUserBundle:AdminUser:groups }
AdminUserBundle_group_edit:
    pattern:  /admin_user_group_edit/{id}
    defaults: { _controller: ScubeAdminUserBundle:AdminUser:editGroup } 