parameters:
#    scube_admin_system.example.class: Scube\AdminSystemBundle\Example

services:
#    scube_admin_system.example:
#        class: %scube_admin_system.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
