parameters:
#    scube_admin_help.example.class: Scube\AdminHelpBundle\Example

services:
#    scube_admin_help.example:
#        class: %scube_admin_help.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
