parameters:
#    widgets_simple_clock.example.class: Widgets\SimpleClockBundle\Example

services:
#    widgets_simple_clock.example:
#        class: %widgets_simple_clock.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
