ScubeMailboxBundle_homepage:
    pattern:  /mailbox
    defaults: { _controller: ScubeMailboxBundle:Mailbox:index }
ScubeMailboxBundle_homepage_conversation:
    pattern:  /mailbox/{id_user}
    defaults: { _controller: ScubeMailboxBundle:Mailbox:index }
ScubeMailboxBundle_ajax_users_list:
    pattern:  /mailbox_ajax_users_list/{search}
    defaults: { _controller: ScubeMailboxBundle:Mailbox:UsersList}
ScubeMailboxBundle_ajax_users_list_noparam:
    pattern:  /mailbox_ajax_users_list
    defaults: { _controller: ScubeMailboxBundle:Mailbox:UsersList }