AdminSettingsBundle_homepage:
    pattern:  /admin_settings
    defaults: { _controller: ScubeAdminSettingsBundle:AdminSettings:index }

AdminSettingsBundle_edit:
    pattern:  /admin_settings_edit/{id}
    defaults: { _controller: ScubeAdminSettingsBundle:AdminSettings:edit }

AdminSettingsBundle_site_infos:
    pattern:  /admin_settings_site_infos
    defaults: { _controller: ScubeAdminSettingsBundle:AdminSettings:siteInfos }