ScubeAccountBundle_homepage:
    pattern:  /edit_account
    defaults: { _controller: ScubeAccountBundle:Account:editAccount }
ScubeAccountBundle_edit_email_password:
    pattern:  /edit_email_password
    defaults: { _controller: ScubeAccountBundle:Account:editEmailPassword }
ScubeAccountBundle_edit_profile:
    pattern:  /edit_profile
    defaults: { _controller: ScubeAccountBundle:Account:editProfile }