parameters:
#    widgets_clock.example.class: Widgets\ClockBundle\Example

services:
#    widgets_clock.example:
#        class: %widgets_clock.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
