_homepage:
    pattern:  /
    defaults: { _controller: ScubeBaseBundle:Base:index }

_register:
    pattern:  /register
    defaults: { _controller: ScubeBaseBundle:Base:register }

_logout:
    pattern:  /logout
    defaults: { _controller: ScubeBaseBundle:Base:logout }

_frame_profile:
    pattern:  /frame_profile
    defaults: { _controller: ScubeBaseBundle:Base:frame_profile }