ScubeManageFileBundle_homepage:
    pattern:  /pictures
    defaults: { _controller: ScubeManageFileBundle:Default:index }

ScubeManageFileBundle_pictures_show:
    pattern:  /pictures/show
    defaults: { _controller: ScubeManageFileBundle:Default:show }

ScubeManageFileBundle_pictures_upload:
    pattern:  /pictures/upload
    defaults: { _controller: 'ScubeManageFileBundle:Default:upload' }
    
ScubeManageFileBundle_pictures_delete:
    pattern:  /pictures/delete
    defaults: { _controller: 'ScubeManageFileBundle:Default:delete' }
