parameters:
#    widgets_calendar_widget.example.class: Widgets\CalendarWidgetBundle\Example

services:
#    widgets_calendar_widget.example:
#        class: %widgets_calendar_widget.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
