parameters:
#    widgets_mailbox_widget.example.class: Widgets\MailboxWidgetBundle\Example

services:
#    widgets_mailbox_widget.example:
#        class: %widgets_mailbox_widget.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
