ScubeAccountBundle_homepage:
    pattern:  /edit_account
    defaults: { _controller: ScubeAccountBundle:Account:editAccount }
ScubeAccountBundle_edit_email_password:
    pattern:  /edit_email_password
    defaults: { _controller: ScubeAccountBundle:Account:editEmailPassword }
ScubeAccountBundle_edit_profile:
    pattern:  /edit_profile
    defaults: { _controller: ScubeAccountBundle:Account:editProfile }
ScubeAccountBundle_edit_picture:
    pattern:  /edit_picture
    defaults: { _controller: ScubeAccountBundle:Account:editPicture }
ScubeAccountBundle_crop_profile_picture:
    pattern:  /crop_profile_picture
    defaults: { _controller: ScubeAccountBundle:Account:cropProfilePicture }