Scube\ManageFileBundle\Entity\File:
    properties:
        file:
            - File:
                maxSize: 1024M
                mimeTypes: [video/*, image/svg+xml, image/png, image/jpeg, image/gif, application/pdf, application/x-pdf]
                mimeTypesMessage: Pictures, Video or PDF Only
                
Scube\ManageFileBundle\Entity\Picture:
    properties:
        file:
            - Picture:
                maxSize: 4M
                mimeTypes: [image/svg+xml, image/png, image/jpeg, image/gif]
                mimeTypesMessage: Pictures Only
                
Scube\ManageFileBundle\Entity\Video:
    properties:
        file:
            - Video:
                maxSize: 1024M
                mimeTypes: []
                mimeTypesMessage: Videos Only
                
Scube\ManageFileBundle\Entity\PDF:
    properties:
        file:
            - PDF:
                maxSize: 16M
                mimeTypes: [application/pdf, application/x-pdf]
                mimeTypesMessage: PDF only
                