parameters:
#    scube_connections.example.class: Scube\ConnectionsBundle\Example

services:
#    scube_connections.example:
#        class: %scube_connections.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
