ScubeMediasBundle:
    resource: "@ScubeMediasBundle/Resources/config/routing.yml"
    prefix:   /

ScubeAdminAppearanceBundle:
    resource: "@ScubeAdminAppearanceBundle/Resources/config/routing.yml"
    prefix:   /

ScubeMailboxBundle:
    resource: "@ScubeMailboxBundle/Resources/config/routing.yml"
    prefix:   /

ScubeCalendarBundle:
    resource: "@ScubeCalendarBundle/Resources/config/routing.yml"
    prefix:   /

ScubeProfileViewerBundle:
    resource: "@ScubeProfileViewerBundle/Resources/config/routing.yml"
    prefix:   /

ScubeMyAppsBundle:
    resource: "@ScubeMyAppsBundle/Resources/config/routing.yml"
    prefix:   /

ScubeAccountBundle:
    resource: "@ScubeAccountBundle/Resources/config/routing.yml"
    prefix:   /

WidgetsConnectionsWidgetBundle:
    resource: "@WidgetsConnectionsWidgetBundle/Resources/config/routing.yml"
    prefix:   /

ScubeConnectionsBundle:
    resource: "@ScubeConnectionsBundle/Resources/config/routing.yml"
    prefix:   /

ScubeAdminUserBundle:
    resource: "@ScubeAdminUserBundle/Resources/config/routing.yml"
    prefix:   /

ScubeInstallBundle:
    resource: "@ScubeInstallBundle/Resources/config/routing.yml"
    prefix:   /

ScubeBaseBundle:
    resource: "@ScubeBaseBundle/Resources/config/routing.yml"
    prefix:   /

ScubeAdminAppsBundle:
    resource: "@ScubeAdminAppsBundle/Resources/config/routing.yml"
    prefix:   /

ScubeAdminSettingsBundle:
    resource: "@ScubeAdminSettingsBundle/Resources/config/routing.yml"
    prefix:   /

ScubeAdminLogsBundle:
    resource: "@ScubeAdminLogsBundle/Resources/config/routing.yml"
    prefix:   /

#APP_DELIMITER

# Internal routing configuration to handle ESI
#_internal:
#   resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#   prefix:   /_internal
