parameters:
#    scube_mailbox.example.class: Scube\MailboxBundle\Example

services:
#    scube_mailbox.example:
#        class: %scube_mailbox.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
