parameters:
#    scube_admin_user.example.class: Scube\AdminUserBundle\Example

services:
#    scube_admin_user.example:
#        class: %scube_admin_user.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
