_homepage:
    pattern:  /
    defaults: { _controller: ScubeBaseBundle:Base:index }

_register:
    pattern:  /register
    defaults: { _controller: ScubeBaseBundle:Base:register }

_logout:
    pattern:  /logout
    defaults: { _controller: ScubeBaseBundle:Base:logout }

_frame_profile:
    pattern:  /frame_profile
    defaults: { _controller: ScubeBaseBundle:Base:frame_profile }

_edit_profile:
    pattern:  /edit_profile
    defaults: { _controller: ScubeBaseBundle:Base:editProfile }
_edit_account:
    pattern:  /edit_account
    defaults: { _controller: ScubeBaseBundle:Base:editAccount }
_my_apps:
    pattern:  /my_apps
    defaults: { _controller: ScubeBaseBundle:Base:myApps }
_my_widgets:
    pattern:  /my_widgets
    defaults: { _controller: ScubeBaseBundle:Base:myWidgets }
_add_widget:
    pattern:  /add_widget
    defaults: { _controller: ScubeBaseBundle:Base:addWidget }
_save_widget_position:
    pattern:  /save_widget_position/{widget_id}/{pos_x}/{pos_y}
    defaults: { _controller: ScubeBaseBundle:Base:saveWidgetPosition }
_save_widget_position_noparam:
    pattern:  /save_widget_position
    defaults: { _controller: ScubeBaseBundle:Base:saveWidgetPosition }
_delete_widget:
    pattern:  /delete_widget/{id}
    defaults: { _controller: ScubeBaseBundle:Base:deleteWidget }
_delete_widget_noparam:
    pattern:  /delete_widget
    defaults: { _controller: ScubeBaseBundle:Base:deleteWidget }