ScubeMediasBundle_homepage:
    pattern:  /medias
    defaults: { _controller: ScubeMediasBundle:Medias:index }
ScubeMediasBundle_homepage_folder:
    pattern:  /medias/{id}
    defaults: { _controller: ScubeMediasBundle:Medias:index }
ScubeMediasBundle_load:
    pattern:  /medias_load/{id}
    defaults: { _controller: ScubeMediasBundle:Medias:load }
ScubeMediasBundle_load_noparam:
    pattern:  /medias_load
    defaults: { _controller: ScubeMediasBundle:Medias:load }
ScubeMediasBundle_delete_folder:
    pattern:  /medias_delete_folder/{id}
    defaults: { _controller: ScubeMediasBundle:Medias:deleteFolder }
ScubeMediasBundle_delete_media:
    pattern:  /medias_delete_media/{id}
    defaults: { _controller: ScubeMediasBundle:Medias:deleteMedia }