AdminUserBundle_homepage:
    pattern:  /admin_user
    defaults: { _controller: ScubeAdminUserBundle:AdminUser:index }
AdminUserBundle_user_add:
    pattern:  /admin_user_add
    defaults: { _controller: ScubeAdminUserBundle:AdminUser:addUser }
AdminUserBundle_user_edit:
    pattern:  /admin_user_edit/{id}
    defaults: { _controller: ScubeAdminUserBundle:AdminUser:editUser }
AdminUserBundle_user_remove:
    pattern:  /admin_user_remove/{id}
    defaults: { _controller: ScubeAdminUserBundle:AdminUser:removeUser }

AdminUserBundle_groups:
    pattern:  /admin_user_groups
    defaults: { _controller: ScubeAdminUserBundle:AdminUser:groups }
AdminUserBundle_group_add:
    pattern:  /admin_user_group_add
    defaults: { _controller: ScubeAdminUserBundle:AdminUser:addGroup}
AdminUserBundle_group_edit:
    pattern:  /admin_user_group_edit/{id}
    defaults: { _controller: ScubeAdminUserBundle:AdminUser:editGroup }
AdminUserBundle_group_remove:
    pattern:  /admin_user_group_remove/{id}
    defaults: { _controller: ScubeAdminUserBundle:AdminUser:removeGroup }