parameters:
#    scube_gold_book.example.class: Scube\GoldBookBundle\Example

services:
#    scube_gold_book.example:
#        class: %scube_gold_book.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
