parameters:
#    scube_friends.example.class: Scube\FriendsBundle\Example

services:
#    scube_friends.example:
#        class: %scube_friends.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
